apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - name: container
          image: backend-cmcustom:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: deployment
spec:
  type: NodePort
  selector:
    app: deployment
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000  # หรือจะลบออกให้ระบบเลือกเองก็ได้
